function plot2D(filtered_NMR,contourlines)
% INPUT VARIABLES
% filtered_NMR: the 2D NMR spectrum. This is generated by the VOI2D
%   function.
% contourlines: the number of contour lines. If the contour 
%   representation is not desired, then type 'no-lines' instead.

if (nargin < 2);
    contourlines=30;
end

NMRshort=filtered_NMR(2:end,2:end);
ppm2=filtered_NMR(1,2:end);
ppm1=filtered_NMR(2:end,1);

if isnumeric(contourlines)
    contour(ppm2,ppm1,NMRshort,contourlines)
    set(gca,'xdir','reverse')
    set(gca,'ydir','reverse')
    xlabel('f2')
    ylabel('f1')
elseif strcmp(contourlines,'no-lines')
    NMRshort(NMRshort~=0)=1;
    red = [1 1 1
    0 0 1];
    colormap(red)
    imagesc(ppm2,ppm1,NMRshort)
    set(gca,'xdir','reverse')
    set(gca,'ydir','reverse')
    xlabel('f2')
    ylabel('f1')
else
    display("Error setting the value of 'level' variable.")
    display("It should be numeric or the string 'no-contour")
end
